### ISSUE TITLE
do you plan to support order and limit+offset ? 

### ISSUE THREAD

**Issue by watsy0007** [awesometoolbox/ormantic#6]

**Comment by hexazero** [comment]
My goal with this project is to try and track the original encode/orm project as best as I can for a multitude of reasons (library switching costs, effort, etc.)

This is being tracked here:
https://github.com/encode/orm/pull/30

Looks like limit is merged in:
https://github.com/encode/orm/pull/22

And offset has an open PR:
https://github.com/encode/orm/pull/30

Code looks good if anyone else wants to try their hand at migrating it. But I will likely need this soon myself, so will eventually tackle it.
